server:
  port: 8769

spring:
  application:
    name: auth-server

eureka:
  client:
        # Spring Cloud Eureka 注册中心地址
    service-url:
      #指定服务中心地址
      defaultZone: http://turbid:turbid321@localhost:8000/eureka/
    register-with-eureka: true